/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdditionalMetrics {
  'precipitation' : number,
  'sunriseTime' : Time,
  'sunsetTime' : Time,
  'airQualityIndex' : bigint,
}
export interface CityWeather {
  'metrics' : AdditionalMetrics,
  'hourlyForecast' : Array<HourlyForecast>,
  'dailyForecast' : Array<DayForecast>,
  'current' : WeatherCondition,
}
export interface DayForecast {
  'low' : number,
  'high' : number,
  'condition' : string,
}
export interface HourlyForecast {
  'temperature' : number,
  'hour' : bigint,
  'condition' : string,
}
export type Time = bigint;
export interface WeatherCondition {
  'temperature' : number,
  'pressure' : bigint,
  'windSpeed' : number,
  'uvIndex' : number,
  'humidity' : bigint,
  'feelsLike' : number,
  'visibility' : number,
  'condition' : string,
}
export interface _SERVICE {
  'addCity' : ActorMethod<[string, CityWeather], undefined>,
  'getAdditionalMetrics' : ActorMethod<[[] | [string]], AdditionalMetrics>,
  'getAllCities' : ActorMethod<[], Array<string>>,
  'getCurrentWeather' : ActorMethod<[[] | [string]], WeatherCondition>,
  'getDailyForecast' : ActorMethod<[[] | [string]], Array<DayForecast>>,
  'getHourlyForecast' : ActorMethod<[[] | [string]], Array<HourlyForecast>>,
  'searchCities' : ActorMethod<[string], Array<string>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];