/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const AdditionalMetrics = IDL.Record({
  'precipitation' : IDL.Float64,
  'sunriseTime' : Time,
  'sunsetTime' : Time,
  'airQualityIndex' : IDL.Nat,
});
export const HourlyForecast = IDL.Record({
  'temperature' : IDL.Float64,
  'hour' : IDL.Nat,
  'condition' : IDL.Text,
});
export const DayForecast = IDL.Record({
  'low' : IDL.Float64,
  'high' : IDL.Float64,
  'condition' : IDL.Text,
});
export const WeatherCondition = IDL.Record({
  'temperature' : IDL.Float64,
  'pressure' : IDL.Nat,
  'windSpeed' : IDL.Float64,
  'uvIndex' : IDL.Float64,
  'humidity' : IDL.Nat,
  'feelsLike' : IDL.Float64,
  'visibility' : IDL.Float64,
  'condition' : IDL.Text,
});
export const CityWeather = IDL.Record({
  'metrics' : AdditionalMetrics,
  'hourlyForecast' : IDL.Vec(HourlyForecast),
  'dailyForecast' : IDL.Vec(DayForecast),
  'current' : WeatherCondition,
});

export const idlService = IDL.Service({
  'addCity' : IDL.Func([IDL.Text, CityWeather], [], []),
  'getAdditionalMetrics' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [AdditionalMetrics],
      ['query'],
    ),
  'getAllCities' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCurrentWeather' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [WeatherCondition],
      ['query'],
    ),
  'getDailyForecast' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(DayForecast)],
      ['query'],
    ),
  'getHourlyForecast' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(HourlyForecast)],
      ['query'],
    ),
  'searchCities' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const AdditionalMetrics = IDL.Record({
    'precipitation' : IDL.Float64,
    'sunriseTime' : Time,
    'sunsetTime' : Time,
    'airQualityIndex' : IDL.Nat,
  });
  const HourlyForecast = IDL.Record({
    'temperature' : IDL.Float64,
    'hour' : IDL.Nat,
    'condition' : IDL.Text,
  });
  const DayForecast = IDL.Record({
    'low' : IDL.Float64,
    'high' : IDL.Float64,
    'condition' : IDL.Text,
  });
  const WeatherCondition = IDL.Record({
    'temperature' : IDL.Float64,
    'pressure' : IDL.Nat,
    'windSpeed' : IDL.Float64,
    'uvIndex' : IDL.Float64,
    'humidity' : IDL.Nat,
    'feelsLike' : IDL.Float64,
    'visibility' : IDL.Float64,
    'condition' : IDL.Text,
  });
  const CityWeather = IDL.Record({
    'metrics' : AdditionalMetrics,
    'hourlyForecast' : IDL.Vec(HourlyForecast),
    'dailyForecast' : IDL.Vec(DayForecast),
    'current' : WeatherCondition,
  });
  
  return IDL.Service({
    'addCity' : IDL.Func([IDL.Text, CityWeather], [], []),
    'getAdditionalMetrics' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [AdditionalMetrics],
        ['query'],
      ),
    'getAllCities' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCurrentWeather' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [WeatherCondition],
        ['query'],
      ),
    'getDailyForecast' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(DayForecast)],
        ['query'],
      ),
    'getHourlyForecast' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(HourlyForecast)],
        ['query'],
      ),
    'searchCities' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };